# Client field labels from Oracle Forms / blueprint.md / screenshots.
# Copyright (c) 2026, Millitrix and contributors

from __future__ import annotations

# Shared across many transaction / master forms (Oracle column → label).
COMMON_FIELD_LABELS: dict[str, str] = {
	"location_id": "Location",
	"partyid": "Party",
	"itemcode": "Item",
	"brokerid": "Broker",
	"supplierid": "Supplier",
	"customerid": "Customer",
	"sub_partyid": "Sub Party",
	"cityid": "City",
	"doctypeid": "Doc Type ID",
	"accid": "A/c Id",
	"empno": "Employee",
	"debit": "Debit",
	"credit": "Credit",
	"balance": "Balance",
	"trans_id": "Transaction",
	"storeid": "Store",
	"tostoreid": "To Store",
	"fromstoreid": "From Store",
	"bagid": "Bardana Bag Item",
	"bagitemcode": "Bardana Bag Item",
	"truckno": "Truck Number",
	"truckqty": "Truck Quantity",
	"bagqty": "Bag Quantity",
	"bagweight": "Bag Weight",
	"inkanta": "In Kanta",
	"delikanta": "Delivery Kanta",
	"lessweight": "Less Weight",
	"dust": "Dust",
	"netweight": "Net Weight",
	"rate": "Rate",
	"totalamnt": "Total Amount",
	"brokeramnt": "Broker Amount",
	"bags_are": "Bags Are",
	"cartage": "Cartage",
	"bagrate": "Bag Rate",
	"discount": "Discount",
	"labouramnt": "Labour Amount",
	"transporter": "Transporter",
	"gprefeno": "Gate Pass Reference",
	"biltyno": "Bilty Number",
	"truckadv": "Truck Advance",
	"emptybags": "Empty Bags",
	"kantatype": "Kanta Type",
	"mundtype": "Mund Type",
	"amount_by": "Amount By",
	"remarks": "Remarks",
	"gptype": "Gate Pass Type",
	"gpdate": "Gate Pass Date",
	"gatepassno": "Gate Pass Number",
	"documentid": "Document Number",
	"ponumber": "Purchase Order Number",
	"sonumber": "Sales Order Number",
	"purchinvno": "Purchase Invoice Number",
	"salesinvno": "Sales Invoice Number",
	"podate": "Order Date",
	"sodate": "Order Date",
	"invdate": "Invoice Date",
	"status": "Status",
	"potype": "Order Type",
	"sotype": "Order Type",
	"payable": "Payable",
	"receivable": "Receivable",
	"amount": "Amount",
	"brokery": "Brokery",
	"brokerypayable": "Brokery Payable",
	"quantity": "Quantity",
	"opening_stock": "Opening Stock",
	"closing_stock": "Closing Stock",
	"movingrate": "Moving Rate",
	"inc_stock": "Increase Stock",
	"dec_stock": "Decrease Stock",
	"transferno": "Transfer Number",
	"tdate": "Transfer Date",
	"in_gprefeno": "In Gate Pass Reference",
	"out_gprefeno": "Out Gate Pass Reference",
	"stkadjid": "ID",
	"sadate": "Date",
	"sopenid": "Document Number",
	"opendate": "Date",
	"crashid": "Crash Refine Number",
	"crdate": "Crash Refine Date",
	"mill_id": "Mill",
	"pnrno": "Voucher Number",
	"pnrdate": "Voucher Date",
	"pnrmode": "Payment Mode",
	"bankaccid": "Bank Account",
	"vouchertype_id": "Voucher Type",
	"voucherno": "Voucher Number",
	"voucherdate": "Voucher Date",
	"description": "Description",
	"narration": "Narration",
	"parentid": "Parent Order Number",
	"moduleid": "Module Number",
	"menuid": "Menu Number",
	"pcat_id": "Party Category",
	"name": "Name",
	"address": "Address",
	"phno1": "Phone Number 1",
	"phno2": "Phone Number 2",
	"mobileno": "Mobile Number",
	"resphno": "Residential Phone",
	"creditlimit": "Credit Limit",
	"creditdays": "Credit Days",
	"itemname": "Item Name",
	"iclassid": "Item Class",
	"stockable": "Stockable",
	"company_id": "Company",
	"short_name": "Short Name",
	"chartlevel": "Chart Level",
	"parentid_coa": "Parent Account",
	"nature": "Account Nature",
	"transflag": "Transaction Allowed",
	"userid": "User",
	"username": "User Name",
	"password": "Password",
	"activestatus": "Active User",
	"canview": "View",
	"canadd": "Add",
	"canedit": "Edit",
	"candelete": "Del",
	"cansubmit": "Post",
	"canassign": "Spec",
	"canunsubmit": "Unsubmit",
	"user_level": "User Level",
	"resaccess": "Restrict",
	"default_store": "Default Store",
	"us_id": "Id",
	"usdate": "Date",
	"usdoctype": "Doc. Type",
	"documentid": "Document Number",
	"usdocumentid": "Document Number",
}

# Form-specific overrides (screenshot / Oracle form titles).
DOCTYPE_FIELD_LABELS: dict[str, dict[str, str]] = {
	"Mill Information": {
		"company_id": "Ref No.",
		"description": "Company Name",
		"phno1": "Phone No.1",
		"phno2": "Phone No.2",
	},
	"City Setup": {
		"cityid": "Ref No.",
		"cityname": "City Name",
	},
	"Departments": {
		"deptid": "Ref No.",
		"description": "Description",
	},
	"Designation": {
		"desigid": "Ref No.",
		"description": "Description",
	},
	"Other Contact Setup": {
		"contactid": "Ref No.",
		"name": "Name",
		"cityid": "City",
		"city_name": "City",
		"phno1": "Phone.01",
		"phno2": "Phone.02",
		"resphno": "Res. Ph.",
		"mobileno": "Mobile",
		"pcat_id": "Category",
	},
	"Location": {
		"location_id": "Ref No.",
		"description": "Mill Name",
		"company_id": "Company",
		"cityid": "City",
	},
	"Bank": {
		"bankid": "Ref No.",
		"shortname": "Short Name",
		"bankname": "Bank Name",
	},
	"Bank Branch": {
		"branchid": "Branch Id",
		"description": "Branch Name",
		"phno1": "Phone.1",
		"phno2": "Phone.2",
	},
	"Bank Account": {
		"branchid": "Branch Id",
		"bankaccid": "A/c Id",
		"accid": "GLCode",
		"acc_description": "Account Name",
		"location_id": "Location Id",
		"location_description": "Location Name",
	},
	"Accounts Opening": {
		"glopenid": "Ref No.",
		"opening_date": "Date",
		"total_debit": "Total Debit",
		"total_credit": "Total Credit",
		"entry_mode": "Entry Type",
		"details": "Details",
		"primary_acc": "Account",
		"line_count": "Lines",
	},
	"Accounts Opening Detail": {
		"accid": "Account",
		"account_description": "Account Name",
		"itemcode": "Item",
		"partyid": "Party",
		"empno": "Employee",
		"trans_id": "Transaction",
	},
	"In Out Gate Pass": {
		"gatepassno": "Gate Pass No.",
		"gpdate": "Date",
		"gptype": "Type",
		"brokerid": "Broker",
		"partyid": "Party",
		"itemcode": "Item",
		"doc_type": "Doc. Type",
		"documentid": "Reference",
		"kantatype": "Kanta Type",
	},
	"Gate Pass Detail": {
		"biltyno": "Bilty No",
		"truckno": "Truck No",
		"truckqty": "Qty",
		"storeid": "Store",
		"emptybags": "Empty",
		"bagid": "Bag",
		"bagqty": "Bag Qty",
		"bagweight": "Per Bag",
		"total_weight": "Total Weight",
		"bags_are": "Bags Are",
	},
	"Opening Stock": {
		"sopenid": "ID",
		"opendate": "Date",
	},
	"Opening Stock Detail": {
		"storeid": "Store_Id",
		"store_name": "Store_Name",
		"itemcode": "ItemCode",
		"item_name": "Item_Name",
		"bagitemcode": "Filled Item",
		"filled_item_name": "Item_Name",
		"partyid": "Party_Id",
		"party_name": "Party_Name",
		"bagweight": "Per Bag",
		"opening_stock": "Stock qty",
		"closing_stock": "Closing",
		"movingrate": "Avg Rate",
		"stock_value": "Stock value",
	},
	"Closing Stock": {
		"sopenid": "Id",
		"opendate": "Date",
		"total_stock": "Total Stock",
	},
	"Crashing Refine": {
		"crashid": "Ref No.",
		"crdate": "Date",
		"mill_id": "Mill",
	},
	"Crash Refine Input": {
		"storeid": "Store",
		"critem": "Item",
		"crbagid": "Bag",
		"bagqty": "Bags/Wgt",
		"bagweight": "Per Bag",
		"total_weight": "Weight",
		"bagdust": "Westage",
		"ref_bags": "Ref. Bags",
		"ref_weight": "Ref. Weight",
		"dip": "Dip",
		"prod_1": "Prod. 1",
		"prod_2": "Prod. 2",
	},
	"Crash Refine Output": {
		"proditem": "Item",
		"storeid": "Store",
	},
	"Item Class": {
		"iclassid": "Ref No.",
		"description": "Description",
	},
	"Item Setup": {
		"itemcode": "Ref No.",
		"iclassid": "Class",
		"class_name": "Class Name",
	},
	"Item Price List": {
		"ipdate": "Date",
		"itemcode": "Item",
		"item_name": "Item Name",
		"iclassid": "Class",
		"location_id": "Location",
		"purchrate": "Purchase Rate",
		"salesrate": "Sales Rate",
		"westage": "Westage",
	},
	"Employee Setup": {
		"location_id": "Mill",
		"empno": "Ref No.",
		"ename": "Employee",
		"ecatid": "Category",
		"category_description": "Category Name",
		"department_name": "Department Name",
		"designation_name": "Designation Name",
		"hiredate": "Hiredate",
		"phno1": "Phone No.",
		"ldate": "Left Date",
	},
	"Party": {
		"partyid": "Ref No.",
		"party_name": "Name",
		"cityid": "City",
		"city_name": "City",
		"creditlimit": "Cr. Limit",
		"creditdays": "Cr. Days",
		"phno1": "Phone.01",
		"phno2": "Phone.02",
		"resphno": "Res. Ph.",
		"mobileno": "Mobile",
	},
	"Party Item": {
		"itemcode": "Item Code",
		"item_name": "Item Name",
		"value_type_1": "Brokery By",
		"value_1": "Value",
		"value_type_2": "Brokery By",
		"value_2": "Value",
	},
	"Chart of Accounting": {
		"accid": "Account Number",
		"description": "Account Name",
		"nature": "Type",
		"transflag": "Transaction",
	},
	"Employee Category": {
		"ecatid": "Ref No.",
		"accid": "GL Account",
		"account_description": "A/c Description",
		"payslip": "PaySlip",
		"description": "Description",
	},
	"PaySlip": {
		"pslipid": "Ref No.",
		"pdate": "Date",
		"paymonth": "Salary Month",
	},
	"PaySlip Detail": {
		"empno": "Employee",
		"amount": "Salary",
		"balance": "Advance",
	},
	"Advance PNR": {
		"pnrno": "Document Id",
		"pnrdate": "Date",
	},
	"Advance Payment": {
		"pnrno": "Ref No.",
		"pnrdate": "Date",
		"partyid": "Party",
		"party_name": "Party",
		"bankaccid": "Bank",
		"bank_name": "Bank",
		"amount": "Advance",
		"pnrmode": "Payment Mode",
	},
	"Advance Receipt": {
		"pnrno": "Ref No.",
		"pnrdate": "Date",
		"partyid": "Customer",
		"party_name": "Customer",
		"bankaccid": "Bank",
		"bank_name": "Bank",
		"pnrmode": "Receipt Mode",
		"amount": "Advance",
	},
	"Purchase Invoice Payment": {
		"pnrno": "Ref No.",
		"pnrdate": "Date",
		"partyid": "Supplier",
		"party_name": "Name",
		"pnrmode": "Payment Mode",
		"amount": "Amount",
		"line_count": "Lines",
	},
	"Sales Invoice Receipt": {
		"pnrno": "Ref No.",
		"pnrdate": "Date",
		"partyid": "Customer",
		"party_name": "Customer Name",
		"pnrmode": "Receipt Mode",
		"amount": "Amount",
		"line_count": "Lines",
	},
	"Broker Invoice Payment": {
		"pnrno": "Ref No.",
		"pnrdate": "Date",
		"partyid": "Broker",
		"party_name": "Name",
		"pnrmode": "Payment Mode",
		"amount": "Amount",
		"line_count": "Lines",
	},
	"Closing and Adjustment Entries": {
		"voucherno": "Ref No.",
		"vouchdate": "Date",
		"submitvoucherno": "Submit Voucher No",
		"reference": "Reference",
		"submitvouchdate": "Submit Date",
		"total_debit": "Total Debit",
		"total_credit": "Total Credit",
		"primary_acc": "Account",
		"line_count": "Lines",
	},
	"Voucher Transaction": {
		"voucherno": "Ref No.",
		"vouchdate": "Date",
		"submitvoucherno": "Submit Voucher No",
		"reference": "Reference",
		"submitvouchdate": "Submit Date",
		"total_debit": "Total Debit",
		"total_credit": "Total Credit",
		"primary_acc": "Account",
		"line_count": "Lines",
	},
	"Payment and Receipt Document": {
		"documentid": "Document Id",
		"party_name": "Party",
	},
	"Payment and Receipt Instrument": {
		"bankaccid": "Bank Id",
		"referdate": "Date",
	},
	"Payable Discount Note": {
		"pnrno": "Ref No.",
		"pnrdate": "Date",
		"partyid": "Supplier",
		"line_count": "Lines",
	},
	"Payment By Hawala": {
		"gmid": "Hawala Id",
		"gmdate": "Date",
		"partyid": "Debit Party",
		"itemcode": "Expense",
		"accid": "Account",
		"gmmode": "Mode",
		"b_partyid": "Credit Party",
		"b_itemcode": "Expense",
		"b_accid": "Account",
		"b_gmmode": "Mode",
	},
	"Hawala Party B": {
		"partyid": "Credit Party",
		"itemcode": "Expense",
		"accid": "Account",
		"gmmode": "Mode",
	},
	"Receivable Discount Note": {
		"pnrno": "Ref No.",
		"pnrdate": "Date",
		"partyid": "Customer",
		"line_count": "Lines",
	},
	"Party Gross Margin": {
		"pgmid": "Ref No.",
		"pgdate": "Date",
		"partyid": "Party",
		"itemcode": "Item",
		"accid": "Account",
		"pgmode": "Mode",
		"amount": "Amount",
		"line_count": "Lines",
	},
	"Payment Voucher": {
		"cnbvno": "Ref No.",
		"vouchdate": "Date",
		"paymode": "Payment Mode",
		"bankaccid": "Bank",
		"amount": "Amount",
		"primary_acc": "Account",
		"line_count": "Lines",
	},
	"Receipt Voucher": {
		"cnbvno": "Ref No.",
		"vouchdate": "Date",
		"paymode": "Receipt Mode",
		"amount": "Amount",
		"primary_acc": "Account",
		"line_count": "Lines",
	},
	"Expense Voucher": {
		"cnbvno": "Ref No.",
		"vouchdate": "Date",
		"paymode": "Voucher Mode",
		"bankaccid": "Bank",
		"amount": "Amount",
		"primary_acc": "Account",
		"line_count": "Lines",
	},
	"Cash and Bank Voucher Detail": {
		"accid": "Account",
		"account_description": "Description",
	},
	"Expense Voucher Detail": {
		"trans_id": "Trans Id",
		"transaction_description": "Description",
		"mill_id": "Mill Id",
	},
	"Employee Payment Voucher": {
		"empvno": "Ref No.",
		"vouchdate": "Date",
		"paymode": "Payment Mode",
		"bankaccid": "Bank",
		"amount": "Amount",
		"primary_employee": "Employee",
		"line_count": "Lines",
	},
	"Employee Receipt Voucher": {
		"empvno": "Ref No.",
		"vouchdate": "Date",
		"paymode": "Receipt Mode",
		"bankaccid": "Bank",
		"amount": "Amount",
		"primary_employee": "Employee",
		"line_count": "Lines",
	},
	"GL Statements": {
		"statementid": "Ref No.",
		"statement": "Statement",
		"description": "Description",
		"active": "Active",
		"operation": "Operation",
		"line_count": "Lines",
		"account_count": "Accounts",
	},
	"GL Statement Account": {
		"accid": "Account",
		"account_description": "Account Name",
		"show_side": "Show Side",
	},
	"Cash and Bank Voucher Document": {
		"empno": "Emp No.",
		"employee_name": "Employee Name",
		"partyid": "Party Id",
		"documentid": "Document Id",
		"docbalamnt": "Payable",
		"amount": "Paid",
	},
	"Party Category": {
		"pcat_id": "Category No.",
		"accid": "A/c Id",
		"account_description": "A/c Description",
		"description": "Description",
	},
	"Transaction Category": {
		"tcat_id": "Category No.",
		"accid": "A/c Id",
		"account_description": "A/c Description",
		"description": "Description",
	},
	"Transaction List": {
		"trans_id": "Ref No.",
		"tcat_id": "Category",
		"category_description": "Category Name",
		"description": "Description",
	},
	"User Rights": {
		"userid": "Ref No.",
		"username": "User Name",
		"erp_user": "ERPNext User",
		"location_id": "Location",
		"empno": "Employee",
		"employee_name": "Employee Name",
		"activestatus": "Active Status",
	},
	"Party Payment Voucher": {
		"cnbvno": "Ref No.",
		"bankaccid": "Bank",
		"vouchdate": "Date",
		"paymode": "Payment Mode",
		"partyid": "Supplier",
		"amount": "Amount",
		"line_count": "Lines",
	},
	"Party Receipt Voucher": {
		"cnbvno": "Ref No.",
		"bankaccid": "Bank",
		"vouchdate": "Date",
		"paymode": "Receipt Mode",
		"partyid": "Customer",
		"amount": "Amount",
		"line_count": "Lines",
	},
	"Paid Advance Adjustment": {
		"adjid": "Ref No.",
		"adjdate": "Date",
		"partyid": "Party",
		"amount": "Amount",
		"line_count": "Lines",
	},
	"Received Advance Adjustment": {
		"adjid": "Ref No.",
		"adjdate": "Date",
		"partyid": "Party",
		"amount": "Amount",
		"line_count": "Lines",
	},
	"Adjustment PNR": {
		"pnrno": "Document Id",
		"pnrdate": "Date",
		"pnrmode": "Mode",
		"accid": "Account Id",
	},
	"Adjustment Invoice": {
		"documentid": "Document_Id",
		"docbalamnt": "Balance",
	},
	"Payment and Receipt Voucher": {
		"pnrno": "Id",
		"pnrdate": "Date",
	},
	"Cash and Bank Voucher": {
		"cnbno": "Id",
		"cnbdate": "Date",
	},
	"Purchase Invoice": {
		"purchinvno": "Ref No.",
		"invdate": "Date",
		"amount": "Invoice Amount",
		"brokery_auto_calc": "Auto",
		"brokery_dr_supplier": "Debit Supplier",
	},
	"Purchase Invoice Detail": {
		"ponumber": "PO",
		"biltyno": "Bilty No",
		"truckno": "Truck No",
		"truckadv": "Truck Adv",
		"truckqty": "Quantity",
		"storeid": "Store",
		"bagid": "Bag",
		"bagqty": "Bag Qty",
		"bagweight": "Per Bag",
		"inkanta": "In kanta",
		"delikanta": "Delivery kanta",
		"lessweight": "Less",
		"gprefeno": "GatePass",
	},
	"Sales Invoice": {
		"salesinvno": "Invoice No",
		"invdate": "Date",
		"amount": "Invoice Amount",
		"brokery_auto_calc": "Auto",
	},
	"Sales Invoice Detail": {
		"sonumber": "S.O Number",
		"biltyno": "Bilty No",
		"truckno": "Truck No",
		"truckadv": "Truck Adv",
		"truckqty": "Quantity",
		"storeid": "Store_Id",
		"emptybags": "Empty",
		"bagid": "Bag_Id",
		"bagqty": "Bag Qty",
		"bagweight": "Per Bag",
		"delikanta": "Delivery kanta",
		"lessweight": "Less",
		"gprefeno": "GatePass",
	},
	"Purchase Order": {
		"ponumber": "P.O Number",
		"potype": "Type",
		"podate": "Date",
		"parentid": "Main PO-No.",
		"truckqty": "Trucks / Bags",
		"truckqtycancel": "Cancel Trks/Bags",
		"delistartdate": "Deli Start",
		"delicompdate": "Deli End",
	},
	"PO Cancellation": {
		"pocid": "Ref No.",
		"candate": "Date",
	},
	"PO Cancellation Detail": {
		"ponumber": "PO",
		"itemcode": "Item",
		"truckqty": "Balance Qty",
		"cancelqty": "Cancel Qty",
	},
	"SO Cancellation": {
		"socid": "Cancel Id",
		"candate": "Date",
	},
	"SO Cancellation Detail": {
		"sonumber": "SO Number",
		"itemname": "Item Name",
		"truckqty": "Balance Qty",
		"cancelqty": "Cancel Qty",
	},
	"Sales Order": {
		"sonumber": "S.O Number",
		"sotype": "Type",
		"sodate": "Date",
		"parentid": "Main SONo.",
		"truckqty": "Trucks / Bags",
		"truckqtycancel": "Cancel Trks/Bags",
		"delistartdate": "Deli Start",
		"delicompdate": "Deli End",
	},
	"Sales Other Bill": {
		"sbillno": "Bill No.",
		"billdate": "Date",
		"referno": "Refer No",
	},
	"Sales Return Other Bill": {
		"srbillno": "Return No.",
		"brdate": "Date",
		"referno": "Refer No",
		"sbillno": "Bill No.",
	},
	"Stock Transfer Note": {
		"transferno": "Transfer No.",
		"tdate": "Date",
		"in_gprefeno": "In GatePass",
		"out_gprefeno": "Out GatePass",
	},
	"Un-Submit Documents": {
		"us_id": "Id",
		"usdate": "Date",
		"usdoctype": "Doc. Type",
		"documentid": "Document",
	},
	"Store Setup": {
		"storeid": "Ref No.",
		"trans_allow": "Transaction",
		"storetypeid": "Type",
		"parentid": "Parent Store",
		"store_address": "Address",
	},
	"Store Types": {
		"storetypeid": "Ref No.",
		"description": "Description",
	},
}


def label_for_field(doctype: str, fieldname: str, current: str | None = None) -> str | None:
	"""Return client label if defined, else None to keep current."""
	if fieldname in DOCTYPE_FIELD_LABELS.get(doctype, {}):
		return DOCTYPE_FIELD_LABELS[doctype][fieldname]
	if fieldname in COMMON_FIELD_LABELS:
		return COMMON_FIELD_LABELS[fieldname]
	return None
