# Copyright (c) 2026, Millitrix and contributors
# Premium list view plan — human-readable columns & filters per DocType.
#
# Rule: client finds entries by Date, Party, Item, Mill, Amount — NOT by internal ID.
# IDs (Ref No / name) go LAST in column list. First column = title_field (name, not ID).

from __future__ import annotations

# Column order for parent list views (in_list_view). Ref/id fields last.
PARENT_LIST_COLUMNS: dict[str, list[str]] = {
	"Crashing Refine": [
		"crdate",
		"mill_id",
		"primary_item",
		"primary_output",
		"input_weight",
		"crashid",
	],
	"Purchase Invoice": [
		"invdate",
		"itemcode",
		"supplierid",
		"brokerid",
		"kantatype",
		"amount",
		"payable",
		"purchinvno",
	],
	"Sales Invoice": [
		"invdate",
		"itemcode",
		"customerid",
		"brokerid",
		"kantatype",
		"amount",
		"receivable",
		"salesinvno",
	],
	"Purchase Order": ["podate", "itemcode", "supplierid", "brokerid", "rate", "amount", "status", "ponumber"],
	"Purchase Other Bill": ["billdate", "partyid", "amount", "pbillno"],
	"Sales Order": ["sodate", "itemcode", "customerid", "brokerid", "rate", "amount", "status", "sonumber"],
	"In Out Gate Pass": ["gpdate", "gptype", "itemcode", "partyid", "gatepassno"],
	"PaySlip": ["paymonth", "pdate", "primary_employee", "employee_count", "total_salary", "remarks", "pslipid"],
	"PO Cancellation": [
		"candate",
		"partyid",
		"primary_item",
		"total_cancel_qty",
		"line_count",
		"remarks",
		"pocid",
	],
	"Menu": ["description", "parentid", "sortby", "menuid"],
	"Module": ["module", "menuid", "nature", "moduletype", "runtimefile", "doctypeid", "moduleid"],
	"Location": ["description", "short_name", "company_id", "cityid", "phno1", "address", "location_id"],
	"Mill Information": ["description", "short_name", "phno1", "address", "company_id"],
	"City Setup": ["cityname", "cityid"],
	"Departments": ["description", "deptid"],
	"Designation": ["description", "desigid"],
	"Party": ["party_name", "cityid", "mobileno", "phno1", "creditlimit", "pcat_id", "partyid"],
	"Bank": ["bankname", "shortname", "branch_count", "account_count", "bankid"],
	"Employee Setup": [
		"ename",
		"location_id",
		"deptid",
		"desigid",
		"ecatid",
		"salary",
		"phno1",
		"empno",
	],
	"Store Setup": [
		"store_name",
		"trans_allow",
		"storetypeid",
		"location_id",
		"store_address",
		"storeid",
	],
	"Store Types": ["description", "storetypeid"],
	"Item Class": ["description", "iclassid"],
	"Item Setup": ["itemname", "iclassid", "mundtype", "stockable", "itemcode"],
	"Item Price List": [
		"ipdate",
		"location_id",
		"itemcode",
		"iclassid",
		"purchrate",
		"salesrate",
		"westage",
	],
	"Other Contact Setup": [
		"name",
		"cityid",
		"pcat_id",
		"mobileno",
		"phno1",
		"address",
		"contactid",
	],
	"Party Category": ["description", "accid", "account_description", "pcat_id"],
	"Employee Category": ["description", "accid", "account_description", "payslip", "ecatid"],
	"Transaction Category": ["description", "accid", "account_description", "tcat_id"],
	"Transaction List": ["description", "tcat_id", "category_description", "trans_id"],
	"User Rights": ["username", "erp_user", "location_id", "empno", "employee_name", "activestatus", "userid"],
	"Purchase Invoice Payment": ["pnrdate", "partyid", "pnrmode", "amount", "line_count", "narration", "pnrno"],
	"Sales Invoice Receipt": ["pnrdate", "partyid", "pnrmode", "amount", "line_count", "narration", "pnrno"],
	"Broker Invoice Payment": ["pnrdate", "partyid", "pnrmode", "amount", "line_count", "narration", "pnrno"],
	"Advance Payment": ["pnrdate", "partyid", "pnrmode", "amount", "narration", "pnrno"],
	"Advance Receipt": ["pnrdate", "partyid", "pnrmode", "amount", "narration", "pnrno"],
	"Payable Discount Note": ["pnrdate", "partyid", "amount", "line_count", "narration", "pnrno"],
	"Receivable Discount Note": ["pnrdate", "partyid", "amount", "line_count", "narration", "pnrno"],
	"Party Gross Margin": ["pgdate", "partyid", "itemcode", "amount", "line_count", "pgmode", "narration", "pgmid"],
	"Party Payment Voucher": [
		"vouchdate",
		"partyid",
		"paymode",
		"amount",
		"line_count",
		"narration",
		"cnbvno",
	],
	"Party Receipt Voucher": [
		"vouchdate",
		"partyid",
		"paymode",
		"amount",
		"line_count",
		"narration",
		"cnbvno",
	],
	"Payment Voucher": [
		"vouchdate",
		"primary_acc",
		"paymode",
		"amount",
		"line_count",
		"narration",
		"cnbvno",
	],
	"Receipt Voucher": [
		"vouchdate",
		"primary_acc",
		"paymode",
		"amount",
		"line_count",
		"narration",
		"cnbvno",
	],
	"Expense Voucher": [
		"vouchdate",
		"primary_acc",
		"paymode",
		"amount",
		"line_count",
		"narration",
		"cnbvno",
	],
	"Employee Payment Voucher": [
		"vouchdate",
		"primary_employee",
		"paymode",
		"amount",
		"line_count",
		"narration",
		"empvno",
	],
	"Employee Receipt Voucher": [
		"vouchdate",
		"primary_employee",
		"paymode",
		"amount",
		"line_count",
		"narration",
		"empvno",
	],
	"Accounts Opening": [
		"opening_date",
		"primary_acc",
		"line_count",
		"total_debit",
		"total_credit",
		"glopenid",
	],
	"GL Statements": [
		"statement",
		"description",
		"active",
		"operation",
		"line_count",
		"account_count",
		"statementid",
	],
	"Purchase Return": [
		"retdate",
		"itemcode",
		"supplierid",
		"brokerid",
		"purchinvno",
		"amount",
		"purchretno",
	],
	"Purchase Return Other Bill": ["brdate", "partyid", "pbillno", "amount", "prbillno"],
	"Sales Return": [
		"retdate",
		"itemcode",
		"customerid",
		"brokerid",
		"salesinvno",
		"amount",
		"salesretno",
	],
	"Sales Return Other Bill": ["brdate", "partyid", "sbillno", "amount", "srbillno"],
	"Sales Other Bill": ["billdate", "partyid", "amount", "sbillno"],
	"SO Cancellation": [
		"candate",
		"partyid",
		"primary_item",
		"total_cancel_qty",
		"line_count",
		"remarks",
		"socid",
	],
	"Stock Adjustment": [
		"sadate",
		"primary_item",
		"primary_store",
		"line_count",
		"total_amount",
		"remarks",
		"stkadjid",
	],
	"Opening Stock": [
		"opendate",
		"primary_item",
		"primary_store",
		"line_count",
		"total_stock_value",
		"sopenid",
	],
	"Closing Stock": [
		"opendate",
		"primary_item",
		"primary_store",
		"line_count",
		"total_stock",
		"remarks",
		"sopenid",
	],
	"Stock Transfer Note": [
		"tdate",
		"itemcode",
		"fromstoreid",
		"primary_tostore",
		"line_count",
		"total_netweight",
		"transferno",
	],
	"Un-Submit Documents": [
		"usdate",
		"usdoctype",
		"documentid",
		"doc_description",
		"remarks",
		"us_id",
	],
	"Paid Advance Adjustment": [
		"adjdate",
		"partyid",
		"amount",
		"line_count",
		"narration",
		"adjid",
	],
	"Received Advance Adjustment": [
		"adjdate",
		"partyid",
		"amount",
		"line_count",
		"narration",
		"adjid",
	],
	"Chart of Accounting": [
		"description",
		"nature",
		"chartlevel",
		"parentid",
		"transflag",
		"accid",
	],
	"Closing and Adjustment Entries": [
		"vouchdate",
		"narration",
		"reference",
		"primary_acc",
		"line_count",
		"total_debit",
		"total_credit",
		"voucherno",
	],
	"Voucher Transaction": [
		"vouchdate",
		"narration",
		"reference",
		"primary_acc",
		"line_count",
		"total_debit",
		"total_credit",
		"voucherno",
	],
}

# First list column (Subject) — Link/Data name clients recognise.
TITLE_FIELDS: dict[str, str] = {
	"Crashing Refine": "primary_item",
	"Purchase Invoice": "itemcode",
	"Sales Invoice": "itemcode",
	"Purchase Order": "itemcode",
	"Purchase Other Bill": "partyid",
	"Sales Order": "itemcode",
	"Sales Other Bill": "partyid",
	"In Out Gate Pass": "itemcode",
	"PaySlip": "paymonth",
	"PO Cancellation": "partyid",
	"Purchase Return": "itemcode",
	"Purchase Return Other Bill": "partyid",
	"Sales Return": "itemcode",
	"Sales Return Other Bill": "partyid",
	"SO Cancellation": "partyid",
	"Stock Adjustment": "primary_item",
	"Opening Stock": "primary_item",
	"Closing Stock": "primary_item",
	"Stock Transfer Note": "itemcode",
	"Un-Submit Documents": "documentid",
	"Paid Advance Adjustment": "partyid",
	"Received Advance Adjustment": "partyid",
	"Chart of Accounting": "description",
	"Closing and Adjustment Entries": "narration",
	"Voucher Transaction": "narration",
	"Payment Voucher": "amount",
	"Receipt Voucher": "amount",
	"Expense Voucher": "amount",
	"Party Payment Voucher": "partyid",
	"Party Receipt Voucher": "partyid",
	"Employee Payment Voucher": "primary_employee",
	"Employee Receipt Voucher": "primary_employee",
	"Accounts Opening": "primary_acc",
	"GL Statements": "description",
	"Advance Payment": "partyid",
	"Advance Receipt": "partyid",
	"Payable Discount Note": "partyid",
	"Receivable Discount Note": "partyid",
	"Party Gross Margin": "partyid",
	"Purchase Invoice Payment": "partyid",
	"Sales Invoice Receipt": "partyid",
	"Broker Invoice Payment": "partyid",
	"Menu": "description",
	"Module": "module",
	"Location": "description",
	"Mill Information": "description",
	"City Setup": "cityname",
	"Departments": "description",
	"Designation": "description",
	"Party": "party_name",
	"Bank": "bankname",
	"Employee Setup": "ename",
	"Store Setup": "store_name",
	"Store Types": "description",
	"Item Class": "description",
	"Item Setup": "itemname",
	"Item Price List": "itemcode",
	"Other Contact Setup": "name",
	"Party Category": "description",
	"Employee Category": "description",
	"Transaction Category": "description",
	"Transaction List": "description",
	"User Rights": "username",
}

# Fields exposed in Filter dropdown (in_standard_filter).
STANDARD_FILTERS: dict[str, list[str]] = {
	"Crashing Refine": ["crdate", "mill_id", "primary_item", "primary_output"],
	"In Out Gate Pass": ["gpdate", "gptype", "itemcode", "partyid", "location_id"],
	"PaySlip": ["pdate", "paymonth", "primary_employee"],
	"PO Cancellation": ["candate", "partyid", "primary_item", "location_id"],
	"Menu": ["description", "parentid"],
	"Module": ["module", "menuid", "moduletype", "nature"],
	"Location": ["description", "short_name", "company_id", "cityid"],
	"Mill Information": ["description", "short_name"],
	"City Setup": ["cityname"],
	"Departments": ["description"],
	"Designation": ["description"],
	"Party": ["party_name", "cityid", "mobileno", "pcat_id"],
	"Bank": ["bankname", "shortname"],
	"Employee Setup": ["ename", "location_id", "deptid", "desigid", "ecatid"],
	"Store Setup": ["store_name", "storetypeid", "location_id", "trans_allow"],
	"Store Types": ["description"],
	"Item Class": ["description"],
	"Item Setup": ["itemname", "iclassid", "mundtype", "stockable"],
	"Item Price List": ["ipdate", "location_id", "itemcode", "iclassid"],
	"Other Contact Setup": ["name", "cityid", "pcat_id", "mobileno"],
	"Party Category": ["description", "accid"],
	"Employee Category": ["description", "accid", "payslip"],
	"Transaction Category": ["description", "accid"],
	"Transaction List": ["description", "tcat_id"],
	"User Rights": ["username", "location_id", "empno", "activestatus"],
	"Purchase Invoice": ["invdate", "itemcode", "supplierid", "brokerid"],
	"Purchase Order": ["podate", "itemcode", "supplierid", "brokerid", "status"],
	"Purchase Other Bill": ["billdate", "partyid"],
	"Purchase Return": ["retdate", "itemcode", "supplierid", "brokerid"],
	"Purchase Return Other Bill": ["brdate", "partyid"],
	"Sales Invoice": ["invdate", "itemcode", "customerid", "brokerid"],
	"Sales Order": ["sodate", "itemcode", "customerid", "brokerid", "status"],
	"Sales Other Bill": ["billdate", "partyid"],
	"Sales Return": ["retdate", "itemcode", "customerid", "brokerid"],
	"Sales Return Other Bill": ["brdate", "partyid"],
	"SO Cancellation": ["candate", "partyid", "primary_item", "location_id"],
	"Stock Adjustment": ["sadate", "primary_item", "primary_store"],
	"Opening Stock": ["opendate", "primary_item", "primary_store"],
	"Closing Stock": ["opendate", "primary_item", "primary_store"],
	"Stock Transfer Note": ["tdate", "itemcode", "fromstoreid"],
	"Un-Submit Documents": ["usdate", "usdoctype", "documentid"],
	"Paid Advance Adjustment": ["adjdate", "partyid"],
	"Received Advance Adjustment": ["adjdate", "partyid"],
	"Chart of Accounting": ["description", "nature", "chartlevel", "transflag"],
	"Closing and Adjustment Entries": ["vouchdate", "primary_acc"],
	"Payment Voucher": ["vouchdate", "primary_acc", "paymode"],
	"Receipt Voucher": ["vouchdate", "primary_acc", "paymode"],
	"Expense Voucher": ["vouchdate", "primary_acc", "paymode"],
	"Party Payment Voucher": ["vouchdate", "partyid", "paymode"],
	"Party Receipt Voucher": ["vouchdate", "partyid", "paymode"],
	"Employee Payment Voucher": ["vouchdate", "primary_employee", "paymode"],
	"Employee Receipt Voucher": ["vouchdate", "primary_employee", "paymode"],
	"Accounts Opening": ["opening_date", "primary_acc"],
	"GL Statements": ["statement", "description", "active"],
	"Advance Payment": ["pnrdate", "partyid", "pnrmode"],
	"Advance Receipt": ["pnrdate", "partyid", "pnrmode"],
	"Payable Discount Note": ["pnrdate", "partyid"],
	"Receivable Discount Note": ["pnrdate", "partyid"],
	"Party Gross Margin": ["pgdate", "partyid", "itemcode"],
	"Purchase Invoice Payment": ["pnrdate", "partyid", "pnrmode"],
	"Sales Invoice Receipt": ["pnrdate", "partyid", "pnrmode"],
	"Broker Invoice Payment": ["pnrdate", "partyid", "pnrmode"],
	"Voucher Transaction": ["vouchdate", "primary_acc"],
}

# Route options keys for deep links (see millitrix_list_filters.js).
ROUTE_FILTER_KEYS: dict[str, list[str]] = {
	"Crashing Refine": [
		"millitrix_mill_id",
		"millitrix_primary_item",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Purchase Invoice": [
		"millitrix_supplierid",
		"millitrix_itemcode",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"In Out Gate Pass": [
		"millitrix_gptype",
		"millitrix_partyid",
		"millitrix_itemcode",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"PaySlip": ["millitrix_from_date", "millitrix_to_date", "millitrix_paymonth"],
	"PO Cancellation": [
		"millitrix_partyid",
		"millitrix_primary_item",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Purchase Return": [
		"millitrix_supplierid",
		"millitrix_itemcode",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Purchase Order": [
		"millitrix_supplierid",
		"millitrix_itemcode",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Purchase Other Bill": [
		"millitrix_partyid",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Purchase Return Other Bill": [
		"millitrix_partyid",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Sales Invoice": [
		"millitrix_customerid",
		"millitrix_itemcode",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Sales Order": [
		"millitrix_customerid",
		"millitrix_itemcode",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Sales Other Bill": [
		"millitrix_partyid",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Sales Return": [
		"millitrix_customerid",
		"millitrix_itemcode",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Sales Return Other Bill": [
		"millitrix_partyid",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"SO Cancellation": [
		"millitrix_partyid",
		"millitrix_primary_item",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Stock Adjustment": [
		"millitrix_primary_item",
		"millitrix_primary_store",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Opening Stock": [
		"millitrix_primary_item",
		"millitrix_primary_store",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Closing Stock": [
		"millitrix_primary_item",
		"millitrix_primary_store",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Stock Transfer Note": [
		"millitrix_itemcode",
		"millitrix_fromstoreid",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Un-Submit Documents": [
		"millitrix_usdoctype",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Paid Advance Adjustment": [
		"millitrix_partyid",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Received Advance Adjustment": [
		"millitrix_partyid",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Chart of Accounting": [
		"millitrix_description",
		"millitrix_nature",
		"millitrix_transflag",
	],
	"Closing and Adjustment Entries": [
		"millitrix_primary_acc",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Payment Voucher": [
		"millitrix_primary_acc",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Receipt Voucher": [
		"millitrix_primary_acc",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Expense Voucher": [
		"millitrix_primary_acc",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Party Payment Voucher": [
		"millitrix_partyid",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Party Receipt Voucher": [
		"millitrix_partyid",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Employee Payment Voucher": [
		"millitrix_primary_employee",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Employee Receipt Voucher": [
		"millitrix_primary_employee",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Accounts Opening": [
		"millitrix_primary_acc",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"GL Statements": [
		"millitrix_statement",
		"millitrix_description",
		"millitrix_active",
	],
	"Advance Payment": [
		"millitrix_partyid",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Advance Receipt": [
		"millitrix_partyid",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Payable Discount Note": [
		"millitrix_partyid",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Receivable Discount Note": [
		"millitrix_partyid",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Party Gross Margin": [
		"millitrix_partyid",
		"millitrix_itemcode",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Purchase Invoice Payment": [
		"millitrix_partyid",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Sales Invoice Receipt": [
		"millitrix_partyid",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Broker Invoice Payment": [
		"millitrix_partyid",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Voucher Transaction": [
		"millitrix_primary_acc",
		"millitrix_from_date",
		"millitrix_to_date",
	],
	"Item Price List": [
		"millitrix_mill_id",
		"millitrix_itemcode",
		"millitrix_from_date",
		"millitrix_to_date",
	],
}
